version: '3.8'

services:
  rowingdata:
    build: .
    ports:
      - "8080:80"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/races"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
